### ISSUE TITLE
Error: Cannot get schema for 'ObjectIdentifier' target

### ISSUE THREAD

**Issue by dchocoboo** [PeculiarVentures/asn1-schema#90]
/node_modules/@peculiar/asn1-schema/build/cjs/schema.js:1
    Error: Cannot get schema for 'ObjectIdentifier' target

      at AsnSchemaStorage.get (node_modules/@peculiar/asn1-schema/build/cjs/schema.js:17:19)
      at Function.toASN (node_modules/@peculiar/asn1-schema/build/cjs/serializer.js:24:48)
      at Function.serialize (node_modules/@peculiar/asn1-schema/build/cjs/serializer.js:14:21)
      at Function.serialize (node_modules/@peculiar/asn1-schema/build/cjs/convert.js:10:43)
      at Function.register (node_modules/webcrypto-core/build/webcrypto-core.js:1144:43)
      at Object.<anonymous> (node_modules/webcrypto-core/build/webcrypto-core.js:1170:10)
      at Object.<anonymous> (node_modules/@peculiar/webcrypto/build/webcrypto.js:7:12)
          at Object.<anonymous> (/node_modules/isomorphic-webcrypto/src/index.js:1)
          at Object.<anonymous> (/node_modules/isomorphic-webcrypto/src/main.js:1)
          at Object.<anonymous> (/node_modules/@pathcheck/dcc-sdk/lib/cose-js/sign.js:1)
          at Object.<anonymous> (/node_modules/@pathcheck/dcc-sdk/lib/dcc.js:1)
          at Object.<anonymous> (/node_modules/@pathcheck/dcc-sdk/lib/main.js:1)

**Comment by dchocoboo** [comment]
dependencies version : 2.3.3

**Comment by microshine** [comment]
Please check that you have only one instance of `@peculiar/asn1-schema` in your project. If it is not, deduplicate it.

```
npm list @peculiar/asn1-schema
```

**Comment by micwallace** [comment]
This same issue happens to me if i `npm link` to a library using asn1-schema. Might be something related to the symlinks used.

**Comment by microshine** [comment]
This error occurs because the `@peculiar/asn1-schema` module registers schemas at the module variable level. If your project includes multiple versions of this module, the schemas might be registered in different instances, leading to this error.

**Comment by ackava** [comment]
@microshine This is a recurring issue, as certificates are used by various packages, every package owner has different versions set as their dependency and even dedup doesn't help if the package owner has set to fixed version e.g. `2.3.13` instead of `^2.3.13`. This causes a deadlock as we cannot upgrade package which has bug fixes along with packages who do not have any bugs but are still dependent on older version.

If schemas would be loaded on demand irrespective of the version, and stored in `globals` using some sort of `Symbol.for("schemas")`, would it not fix the issue?

**Comment by microshine** [comment]
Using a global fallback for the missing schema could indeed fix this — I agree that adding that mechanism makes sense and I plan to include it in a major release.

In the meantime you can work around this by forcing a patched or forked package with your package manager:

- npm: add an "overrides" entry in package.json to point the package (or the nested dependency) to a fixed version or your fork.
- yarn: use "resolutions" in package.json to pin the dependency.
- pnpm: use "overrides" in package.json.
