### ISSUE TITLE
Unable to parse serialized SignedData with crls

### ISSUE THREAD

**Issue by dhensby** [PeculiarVentures/asn1-schema#97]
I've encountered what appears to be a problem with parsing a SignedData object that was serialized with this library. In particular the `crls` seems to be the root of the error. Something about the parser doesn't like the crls property, but I can't quite get to the bottom of why.

When trying to parse the following error is thrown:

```
AsnSchemaValidationError: Data does not match to RevocationInfoChoice ASN1 schema. Wrong values for Choice type
    at Function.fromASN (~/node_modules/@peculiar/asn1-schema/build/cjs/parser.js:43:23)
    at Function.fromASN (~/node_modules/@peculiar/asn1-schema/build/cjs/parser.js:126:41)
    at Function.parse (~/node_modules/@peculiar/asn1-schema/build/cjs/parser.js:16:26)
    at Function.parse (~/node_modules/@peculiar/asn1-schema/build/cjs/convert.js:13:35)
    at Object.<anonymous> (~/minimal.js:119:12)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  schemas: [ 'RevocationInfoChoice', 'SignedData' ]
```

Replication code:

```js
const { randomBytes } = require('crypto');
const { AsnConvert, OctetString, AsnArray, AsnType, AsnTypeTypes, AsnPropTypes } = require('@peculiar/asn1-schema');
const cms = require('@peculiar/asn1-cms');
const { id_sha256, id_rsaEncryption } = require('@peculiar/asn1-rsa');
const { AlgorithmIdentifier, Certificate, Time } = require('@peculiar/asn1-x509');
const { id_pkcs9_at_contentType, id_pkcs9_at_signingTime, id_pkcs9_at_messageDigest } = require('@peculiar/asn1-pkcs9');
const { ObjectIdentifier } = require('asn1js');

// this is a little hack to allow us to define an Asn1 type `Set` which acts as an array
class Set extends AsnArray {}
AsnType({ type: AsnTypeTypes.Set, itemType: AsnPropTypes.Any })(Set);

// the OCSP response and certificate have been fetched from www.akamai.com and digicert
const OCSP_RESPONSE = Buffer.from('MIIB0woBAKCCAcwwggHIBgkrBgEFBQcwAQEEggG5MIIBtTCBnqIWBBS3a6LqqKqEjHnqtNoPmLLFlXa59BgPMjAyMzA5MDcxNDI0NDFaMHMwcTBJMAkGBSsOAwIaBQAEFOTjlaIp09TBwx/wmAwLTsAJiqvYBBS3a6LqqKqEjHnqtNoPmLLFlXa59AIQBkN1zR+sS+PC+kWvOJwagoAAGA8yMDIzMDkwNzE0MDkwMlqgERgPMjAyMzA5MTQxMzA5MDJaMA0GCSqGSIb3DQEBCwUAA4IBAQCJ+sTro/WBdV+megDoNeyQVkYicR+wmLeJGRoj849wgFiSmcSs2YA53EUHt+7Py2eajUmTPLHsFSm5jq9L25cKUdfAFbRoOwE8DxM9af5lA6efYKkz9JRrhrFldpE0nfYxxZLACSompMHoUyF9gXPhmky9ORyMrSiIY4G37ijrhcMML9VM0Gk2bzfnmlFqD7Uh4r+fWptT4GqtuQJ1mmvsV51rWPJXSGKg6OSdQhY/hurfImkXU66YqT5bpzsvPX7qUvkxLCkSeEpnBCrtyaUD3U2j8b1KMQW/FyO5uLp+ktIuImWt2W9XZUmxhzBrynQhK7i5NdBNTvcpaBPUxWH0', 'base64');
const CERTIFICATE = Buffer.from(
    'MIIGAjCCBOqgAwIBAgIQBkN1zR+sS+PC+kWvOJwagjANBgkqhkiG9w0BAQsFADBP' +
    'MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMSkwJwYDVQQDEyBE' +
    'aWdpQ2VydCBUTFMgUlNBIFNIQTI1NiAyMDIwIENBMTAeFw0yMzA0MjUwMDAwMDBa' +
    'Fw0yNDA0MjUyMzU5NTlaMHYxCzAJBgNVBAYTAlVTMRYwFAYDVQQIEw1NYXNzYWNo' +
    'dXNldHRzMRIwEAYDVQQHEwlDYW1icmlkZ2UxIjAgBgNVBAoTGUFrYW1haSBUZWNo' +
    'bm9sb2dpZXMsIEluYy4xFzAVBgNVBAMTDnd3dy5ha2FtYWkuY29tMFkwEwYHKoZI' +
    'zj0CAQYIKoZIzj0DAQcDQgAEazkJqPize87Z0TvOKqKpmfyMOOZotoW2EL4YUz2+' +
    'OEcbZ3SY+aULa2c8/Y15S9ZDa+dssAUZ0r4Zy4x/W7Jx5aOCA3wwggN4MB8GA1Ud' +
    'IwQYMBaAFLdrouqoqoSMeeq02g+YssWVdrn0MB0GA1UdDgQWBBQxd8ph2AKQD7PD' +
    'VrXvZgwe+GZs4DAlBgNVHREEHjAcgg53d3cuYWthbWFpLmNvbYIKYWthbWFpLmNv' +
    'bTAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC' +
    'MIGPBgNVHR8EgYcwgYQwQKA+oDyGOmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9E' +
    'aWdpQ2VydFRMU1JTQVNIQTI1NjIwMjBDQTEtNC5jcmwwQKA+oDyGOmh0dHA6Ly9j' +
    'cmw0LmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRMU1JTQVNIQTI1NjIwMjBDQTEtNC5j' +
    'cmwwPgYDVR0gBDcwNTAzBgZngQwBAgIwKTAnBggrBgEFBQcCARYbaHR0cDovL3d3' +
    'dy5kaWdpY2VydC5jb20vQ1BTMH8GCCsGAQUFBwEBBHMwcTAkBggrBgEFBQcwAYYY' +
    'aHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEkGCCsGAQUFBzAChj1odHRwOi8vY2Fj' +
    'ZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRUTFNSU0FTSEEyNTYyMDIwQ0ExLTEu' +
    'Y3J0MAkGA1UdEwQCMAAwggGABgorBgEEAdZ5AgQCBIIBcASCAWwBagB3AO7N0GTV' +
    '2xrOxVy3nbTNE6Iyh0Z8vOzew1FIWUZxH7WbAAABh7W705QAAAQDAEgwRgIhAPVk' +
    '7yDDPj3tAQc4cvqb9A0B0HjlyhdRFVP/H7/BRNmpAiEAycsOC/0dh53xb/G/BTL6' +
    'GJPQgjc/MtM8D/eWAbCNUKoAdwBIsONr2qZHNA/lagL6nTDrHFIBy1bdLIHZu7+r' +
    'OdiEcwAAAYe1u9PtAAAEAwBIMEYCIQDfupV1HkMJ8PWrMU/1qx6LrJ5UlmKesvqc' +
    '7+87ct4ejwIhAOmSrN2AduhQODpqlLc0cvGzeGXKjIonGkoVRCkv3egyAHYA2ra/' +
    'az+1tiKfm8K7XGvocJFxbLtRhIU0vaQ9MEjX+6sAAAGHtbvTrgAABAMARzBFAiEA' +
    'se+cqNPobp9xgg7xBXa8hGm2Pxdwe+U043YEzlVujPQCIBhYLChVIaCMEDPC9VRv' +
    'q7WJLHNa7WNrqBY2niGEPCFeMA0GCSqGSIb3DQEBCwUAA4IBAQCou6fmQrBrvt7x' +
    'E6rJzQ2OArQWWB7G1UX/NOfkZh3NolCA/b36QNJETbHk2OCGKOwjBdaTsu1ekjI2' +
    'LbzASgM8A0VvsnIIgLawZOzZmKO+OtRzBzNQYm9fkMqoDdY/OqmGrEJ+JwXrg2qz' +
    '8+o5l8Nl7uDf6C3PBpu9w+rWV0arBsSHNWu0Vz82K5031WteXoZdoAJBJJTgjmSE' +
    'UVmhXLWZ0G/JOQlpBk903/JNAtRyReELNxWJCms+OIa3EmelAJ4wbDjHxMqxH2Y2' +
    '+d0jhh/LzTOp8sl2BHlzpMavTX0808PQtO0ywZRCYpPBCPFs4HDDrGwVCVLyevJx' +
    'qaCk2c5Z', 'base64');

const choices = new cms.RevocationInfoChoices([
    new cms.RevocationInfoChoice({
        other: new cms.OtherRevocationInfoFormat({
            otherRevInfoFormat: cms.id_ri_ocsp_response,
            otherRevInfo: OCSP_RESPONSE,
        }),
    }),
]);

// prove we can serialize/parse the cert choices in isolation
AsnConvert.parse(AsnConvert.serialize(choices), cms.RevocationInfoChoices);

// Construct and serialize the SignedData with OCSP response
const certificate = AsnConvert.parse(CERTIFICATE, Certificate);

const signed = AsnConvert.serialize(new cms.SignedData({
    version: cms.CMSVersion.v1,
    digestAlgorithms: new cms.DigestAlgorithmIdentifiers([
        new AlgorithmIdentifier({
            algorithm: id_sha256,
            parameters: null,
        }),
    ]),
    encapContentInfo: new cms.EncapsulatedContentInfo({
        eContentType: cms.id_data,
    }),
    certificates: new cms.CertificateSet([
        new cms.CertificateChoices({ certificate }),
    ]),
    signerInfos: new cms.SignerInfos([
        new cms.SignerInfo({
            version: cms.CMSVersion.v1,
            sid: new cms.SignerIdentifier({
                issuerAndSerialNumber: new cms.IssuerAndSerialNumber({
                    issuer: certificate.tbsCertificate.issuer,
                    serialNumber: certificate.tbsCertificate.serialNumber,
                }),
            }),
            digestAlgorithm: new cms.DigestAlgorithmIdentifier({
                algorithm: id_sha256,
                parameters: null,
            }),
            signedAttrs: new Set([
                new cms.Attribute({
                    type: id_pkcs9_at_contentType,
                    value: new ObjectIdentifier({ value: cms.id_data }),
                }),
                new cms.Attribute({
                    type: id_pkcs9_at_signingTime,
                    value: new Time(new Date()),
                }),
                new cms.Attribute({
                    type: id_pkcs9_at_messageDigest,
                    // fake the detached message digest, it's not important
                    value: new OctetString(randomBytes(32)),
                }),
            ]),
            signatureAlgorithm: new cms.SignatureAlgorithmIdentifier({
                algorithm: id_rsaEncryption,
                parameters: null,
            }),
            // fake the signature, it's not important
            signature: new OctetString(randomBytes(32)),
        }),
    ]),
    crls: choices,
}));

// error is thrown - but it is *not* thrown if the crls are removed
AsnConvert.parse(signed, cms.SignedData);

```

**Comment by dhensby** [comment]
Hey @microshine - sorry to ping directly, I've come up against this again recently and I'm struggling to really understand why or get to the bottom of it.

I've gone through with a debugger and it seems that the ASN.1 parser can't match the value to the correct choice (which is exactly what the error says, so not much better info there) - I'm wondering if this is actually an *encoding* problem rather then a decoding one?!

The problem seems to be that when the parser tries to determine the `OtherRevocationInfoFormat` choice, it is comparing the root contstructed input data against the input sccema, when it should be checking against the first value from the input data (constructed) value block.

It seems that the input data has an *extra* level of `Constucted` that the schema (and/or parser) is not expecting and so it doesn't know how to proceed. In particular is is [here](https://github.com/PeculiarVentures/ASN1.js/blob/v3.0.5/src/schema.ts#L329 where there is an attempt to compare an input `Constructed` with an `ObjectIdentifier` (nb: the first child of the `Constructed` valueBlock is an `ObjectIdentifier`.

I'm not sure if this is a problem with parsing, encoding, or even a shcema definition problem 🤔

**Comment by dhensby** [comment]
I got to the bottom of it, it was a typo/mis-defined prop type in SignedData  see #100
